- name: Gather facts
  hosts: all
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

- name: File to FS\Inventorys\PC
  hosts: all
  become: true
  become_method: sudo
  gather_facts: false
  roles:
    - inventory
